# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  # Update apt-get once
  $update_apt_get = <<SCRIPT
  if ! test -f .updated_apt_get; then
    sudo apt-get update
    touch .updated_apt_get
  fi
SCRIPT
  config.vm.provision "shell", inline: $update_apt_get

  # Install dependencies
  $install_git = <<SCRIPT
  if ! which git &> /dev/null; then
    sudo apt-get install yasm make git build-essential -y
  fi
SCRIPT
  config.vm.provision "shell", inline: $install_git

  # Clone and make the repo
  $build_libav = <<SCRIPT
  CODE_DIR=/vagrant/code/libav
  if ! test -d ${CODE_DIR}/libav/.build; then
    mkdir -p ${CODE_DIR}/
    cd ${CODE_DIR}
    git clone git://git.libav.org/libav
    mkdir libav/.build
    cd ${CODE_DIR}/libav/.build
    ../configure --samples=/vagrant/code/fate
    make
    chown -R vagrant:vagrant /vagrant/code
  fi
SCRIPT
  config.vm.provision "shell", inline: $build_libav

  # Notify the user how to run `fate`
  $notify_user = <<SCRIPT
  echo "\\`libav\\` successfully constructed!"
  echo "To run \\`fate\\`, run the following:"
  echo "vagrant ssh"
  echo "cd /vagrant/code/libav/.build"
  echo "make fate-rsync && make fate"
SCRIPT
  config.vm.provision "shell", inline: $notify_user
end
